<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mergebuilder" nsURI="brgbld" nsPrefix="mrgbld">
  <eClassifiers xsi:type="ecore:EClass" name="Director">
    <eOperations name="mergeSchedule">
      <eParameters name="builder" eType="#//Builder"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Calendar" instanceTypeName="newDataType1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Builder" abstract="true" interface="true">
    <eOperations name="reset"/>
    <eOperations name="importCalendar">
      <eParameters name="calendar" eType="#//Calendar"/>
    </eOperations>
    <eOperations name="parseCalenar">
      <eParameters name="calendar" eType="#//Calendar"/>
    </eOperations>
    <eOperations name="addActivity">
      <eParameters name="calenar" eType="#//Calendar"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergeSchedule" eSuperTypes="#//Builder">
    <eOperations name="generateCalendar" eType="#//Calendar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultCalendar" eType="#//Calendar"/>
  </eClassifiers>
</ecore:EPackage>
